/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "MeiliSearch Documentation",
  "description": "Open source Instant Search Engine",
  "base": "/",
  "pages": [
    {
      "title": "MeiliSearch Documentation",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-03-03T15:52:01.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/"
          },
          {
            "name": "twitter:title",
            "content": "MeiliSearch Documentation"
          },
          {
            "name": "twitter:url",
            "content": "/"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-4df630f4",
      "path": "/",
      "headers": [
        {
          "level": 2,
          "title": "Open-source",
          "slug": "open-source"
        },
        {
          "level": 2,
          "title": "Demo",
          "slug": "demo"
        },
        {
          "level": 2,
          "title": "Alternatives",
          "slug": "alternatives"
        },
        {
          "level": 2,
          "title": "Features",
          "slug": "features"
        }
      ],
      "lastUpdated": "3/3/2020, 4:52:01 PM"
    },
    {
      "title": "MeiliSearch documentation",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-01-26T11:13:29.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "MeiliSearch documentation"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/contributing.html"
          },
          {
            "name": "twitter:title",
            "content": "MeiliSearch documentation"
          },
          {
            "name": "twitter:url",
            "content": "/contributing.html"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/contributing.html",
      "relativePath": "contributing.md",
      "key": "v-7f53ce02",
      "path": "/contributing.html",
      "headers": [
        {
          "level": 2,
          "title": "Installation",
          "slug": "installation"
        },
        {
          "level": 2,
          "title": "Launch",
          "slug": "launch"
        },
        {
          "level": 3,
          "title": "development",
          "slug": "development"
        },
        {
          "level": 2,
          "title": "Changing the documentation",
          "slug": "changing-the-documentation"
        }
      ],
      "lastUpdated": "1/26/2020, 12:13:29 PM"
    },
    {
      "title": "Asynchronous Updates",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-01-10T14:49:20.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Asynchronous Updates"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/guides/advanced_guides/asynchronous_updates.html"
          },
          {
            "name": "twitter:title",
            "content": "Asynchronous Updates"
          },
          {
            "name": "twitter:url",
            "content": "/guides/advanced_guides/asynchronous_updates.html"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/guides/advanced_guides/asynchronous_updates.html",
      "relativePath": "guides/advanced_guides/asynchronous_updates.md",
      "key": "v-51f92432",
      "path": "/guides/advanced_guides/asynchronous_updates.html",
      "headers": [
        {
          "level": 3,
          "title": "Async flow",
          "slug": "async-flow"
        },
        {
          "level": 3,
          "title": "Which operations are async?",
          "slug": "which-operations-are-async"
        },
        {
          "level": 3,
          "title": "Understanding updates",
          "slug": "understanding-updates"
        },
        {
          "level": 3,
          "title": "Examples",
          "slug": "examples"
        }
      ],
      "lastUpdated": "1/10/2020, 3:49:20 PM"
    },
    {
      "title": "Bucket sort",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-02-05T17:04:34.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Bucket sort"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/guides/advanced_guides/bucket_sort.html"
          },
          {
            "name": "twitter:title",
            "content": "Bucket sort"
          },
          {
            "name": "twitter:url",
            "content": "/guides/advanced_guides/bucket_sort.html"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/guides/advanced_guides/bucket_sort.html",
      "relativePath": "guides/advanced_guides/bucket_sort.md",
      "key": "v-976423da",
      "path": "/guides/advanced_guides/bucket_sort.html",
      "lastUpdated": "2/5/2020, 6:04:34 PM"
    },
    {
      "title": "Installation",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-01-26T11:13:29.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Installation"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/guides/advanced_guides/binary.html"
          },
          {
            "name": "twitter:title",
            "content": "Installation"
          },
          {
            "name": "twitter:url",
            "content": "/guides/advanced_guides/binary.html"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/guides/advanced_guides/binary.html",
      "relativePath": "guides/advanced_guides/binary.md",
      "key": "v-202f1227",
      "path": "/guides/advanced_guides/binary.html",
      "headers": [
        {
          "level": 2,
          "title": "Download and launch",
          "slug": "download-and-launch"
        },
        {
          "level": 2,
          "title": "Usage",
          "slug": "usage"
        },
        {
          "level": 2,
          "title": "Environment variables and Flags",
          "slug": "environment-variables-and-flags"
        }
      ],
      "lastUpdated": "1/26/2020, 12:13:29 PM"
    },
    {
      "title": "Concatenate and split queries",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-01-10T14:49:20.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Concatenate and split queries"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/guides/advanced_guides/concat.html"
          },
          {
            "name": "twitter:title",
            "content": "Concatenate and split queries"
          },
          {
            "name": "twitter:url",
            "content": "/guides/advanced_guides/concat.html"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/guides/advanced_guides/concat.html",
      "relativePath": "guides/advanced_guides/concat.md",
      "key": "v-38701fc7",
      "path": "/guides/advanced_guides/concat.html",
      "headers": [
        {
          "level": 2,
          "title": "Concatenated queries",
          "slug": "concatenated-queries"
        },
        {
          "level": 2,
          "title": "Splitted queries",
          "slug": "splitted-queries"
        }
      ],
      "lastUpdated": "1/10/2020, 3:49:20 PM"
    },
    {
      "title": "Distinct",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-02-04T13:11:13.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Distinct"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/guides/advanced_guides/distinct.html"
          },
          {
            "name": "twitter:title",
            "content": "Distinct"
          },
          {
            "name": "twitter:url",
            "content": "/guides/advanced_guides/distinct.html"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/guides/advanced_guides/distinct.html",
      "relativePath": "guides/advanced_guides/distinct.md",
      "key": "v-64df2687",
      "path": "/guides/advanced_guides/distinct.html",
      "headers": [
        {
          "level": 3,
          "title": "Example",
          "slug": "example"
        }
      ],
      "lastUpdated": "2/4/2020, 2:11:13 PM"
    },
    {
      "title": "Guides",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-03-04T12:39:01.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Guides"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/guides/"
          },
          {
            "name": "twitter:title",
            "content": "Guides"
          },
          {
            "name": "twitter:url",
            "content": "/guides/"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/guides/",
      "relativePath": "guides/README.md",
      "key": "v-340cf184",
      "path": "/guides/",
      "lastUpdated": "3/4/2020, 1:39:01 PM"
    },
    {
      "title": "Advanced guides",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-01-10T14:49:20.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Advanced guides"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/guides/advanced_guides/"
          },
          {
            "name": "twitter:title",
            "content": "Advanced guides"
          },
          {
            "name": "twitter:url",
            "content": "/guides/advanced_guides/"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/guides/advanced_guides/",
      "relativePath": "guides/advanced_guides/README.md",
      "key": "v-18d3ace4",
      "path": "/guides/advanced_guides/",
      "lastUpdated": "1/10/2020, 3:49:20 PM"
    },
    {
      "title": "Prefix Search",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-01-26T11:13:29.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Prefix Search"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/guides/advanced_guides/prefix.html"
          },
          {
            "name": "twitter:title",
            "content": "Prefix Search"
          },
          {
            "name": "twitter:url",
            "content": "/guides/advanced_guides/prefix.html"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/guides/advanced_guides/prefix.html",
      "relativePath": "guides/advanced_guides/prefix.md",
      "key": "v-2a351007",
      "path": "/guides/advanced_guides/prefix.html",
      "headers": [
        {
          "level": 3,
          "title": "Example",
          "slug": "example"
        }
      ],
      "lastUpdated": "1/26/2020, 12:13:29 PM"
    },
    {
      "title": "Ranking",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-02-05T16:38:40.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Ranking"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/guides/advanced_guides/ranking.html"
          },
          {
            "name": "twitter:title",
            "content": "Ranking"
          },
          {
            "name": "twitter:url",
            "content": "/guides/advanced_guides/ranking.html"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/guides/advanced_guides/ranking.html",
      "relativePath": "guides/advanced_guides/ranking.md",
      "key": "v-8ee7dc66",
      "path": "/guides/advanced_guides/ranking.html",
      "headers": [
        {
          "level": 2,
          "title": "Ranking rules",
          "slug": "ranking-rules"
        },
        {
          "level": 2,
          "title": "Custom ranking rules",
          "slug": "custom-ranking-rules"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example"
        },
        {
          "level": 2,
          "title": "Ranking order",
          "slug": "ranking-order"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example-2"
        }
      ],
      "lastUpdated": "2/5/2020, 5:38:40 PM"
    },
    {
      "title": "Keys",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-02-05T17:04:34.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Keys"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/guides/advanced_guides/keys.html"
          },
          {
            "name": "twitter:title",
            "content": "Keys"
          },
          {
            "name": "twitter:url",
            "content": "/guides/advanced_guides/keys.html"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/guides/advanced_guides/keys.html",
      "relativePath": "guides/advanced_guides/keys.md",
      "key": "v-4b5f8e07",
      "path": "/guides/advanced_guides/keys.html",
      "headers": [
        {
          "level": 2,
          "title": "Master key",
          "slug": "master-key"
        },
        {
          "level": 2,
          "title": "Creating a key",
          "slug": "creating-a-key"
        },
        {
          "level": 2,
          "title": "Key",
          "slug": "key"
        },
        {
          "level": 2,
          "title": "Description",
          "slug": "description"
        },
        {
          "level": 2,
          "title": "ACL",
          "slug": "acl"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example"
        },
        {
          "level": 2,
          "title": "Indexes",
          "slug": "indexes"
        },
        {
          "level": 2,
          "title": "Revoked",
          "slug": "revoked"
        },
        {
          "level": 2,
          "title": "Expires at",
          "slug": "expires-at"
        }
      ],
      "lastUpdated": "2/5/2020, 6:04:34 PM"
    },
    {
      "title": "Introduction",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-03-04T12:39:01.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Introduction"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/guides/getting_started/"
          },
          {
            "name": "twitter:title",
            "content": "Introduction"
          },
          {
            "name": "twitter:url",
            "content": "/guides/getting_started/"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/guides/getting_started/",
      "relativePath": "guides/getting_started/README.md",
      "key": "v-00fc5ab8",
      "path": "/guides/getting_started/",
      "lastUpdated": "3/4/2020, 1:39:01 PM"
    },
    {
      "title": "Synonyms",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-01-10T14:49:20.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Synonyms"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/guides/advanced_guides/synonyms.html"
          },
          {
            "name": "twitter:title",
            "content": "Synonyms"
          },
          {
            "name": "twitter:url",
            "content": "/guides/advanced_guides/synonyms.html"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/guides/advanced_guides/synonyms.html",
      "relativePath": "guides/advanced_guides/synonyms.md",
      "key": "v-12d6c407",
      "path": "/guides/advanced_guides/synonyms.html",
      "headers": [
        {
          "level": 2,
          "title": "The One-way association",
          "slug": "the-one-way-association"
        },
        {
          "level": 2,
          "title": "The multi-way association",
          "slug": "the-multi-way-association"
        }
      ],
      "lastUpdated": "1/10/2020, 3:49:20 PM"
    },
    {
      "title": "Stop words",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-01-26T11:13:29.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Stop words"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/guides/advanced_guides/stop_words.html"
          },
          {
            "name": "twitter:title",
            "content": "Stop words"
          },
          {
            "name": "twitter:url",
            "content": "/guides/advanced_guides/stop_words.html"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/guides/advanced_guides/stop_words.html",
      "relativePath": "guides/advanced_guides/stop_words.md",
      "key": "v-d7624772",
      "path": "/guides/advanced_guides/stop_words.html",
      "headers": [
        {
          "level": 2,
          "title": "Language driven",
          "slug": "language-driven"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example"
        }
      ],
      "lastUpdated": "1/26/2020, 12:13:29 PM"
    },
    {
      "title": "Typo Tolerance",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-01-26T11:13:29.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Typo Tolerance"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/guides/advanced_guides/typotolerance.html"
          },
          {
            "name": "twitter:title",
            "content": "Typo Tolerance"
          },
          {
            "name": "twitter:url",
            "content": "/guides/advanced_guides/typotolerance.html"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/guides/advanced_guides/typotolerance.html",
      "relativePath": "guides/advanced_guides/typotolerance.md",
      "key": "v-cb40dcb2",
      "path": "/guides/advanced_guides/typotolerance.html",
      "headers": [
        {
          "level": 2,
          "title": "Typo tolerance rules",
          "slug": "typo-tolerance-rules"
        }
      ],
      "lastUpdated": "1/26/2020, 12:13:29 PM"
    },
    {
      "title": "What's next?",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-02-10T15:55:55.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "What's next?"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/guides/getting_started/whats_next.html"
          },
          {
            "name": "twitter:title",
            "content": "What's next?"
          },
          {
            "name": "twitter:url",
            "content": "/guides/getting_started/whats_next.html"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/guides/getting_started/whats_next.html",
      "relativePath": "guides/getting_started/whats_next.md",
      "key": "v-0bfc4927",
      "path": "/guides/getting_started/whats_next.html",
      "lastUpdated": "2/10/2020, 4:55:55 PM"
    },
    {
      "title": "Getting Started",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-03-03T15:43:36.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Getting Started"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/guides/getting_started/quick_start_guide.html"
          },
          {
            "name": "twitter:title",
            "content": "Getting Started"
          },
          {
            "name": "twitter:url",
            "content": "/guides/getting_started/quick_start_guide.html"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/guides/getting_started/quick_start_guide.html",
      "relativePath": "guides/getting_started/quick_start_guide.md",
      "key": "v-f8259c0a",
      "path": "/guides/getting_started/quick_start_guide.html",
      "headers": [
        {
          "level": 2,
          "title": "Download and launch",
          "slug": "download-and-launch"
        },
        {
          "level": 3,
          "title": "Communicate with MeiliSearch",
          "slug": "communicate-with-meilisearch"
        },
        {
          "level": 2,
          "title": "Create your Index",
          "slug": "create-your-index"
        },
        {
          "level": 2,
          "title": "Add Documents",
          "slug": "add-documents"
        },
        {
          "level": 3,
          "title": "Checking updates",
          "slug": "checking-updates"
        },
        {
          "level": 2,
          "title": "Searches",
          "slug": "searches"
        }
      ],
      "lastUpdated": "3/3/2020, 4:43:36 PM"
    },
    {
      "title": "Documents",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-01-10T14:49:20.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Documents"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/guides/main_concepts/documents.html"
          },
          {
            "name": "twitter:title",
            "content": "Documents"
          },
          {
            "name": "twitter:url",
            "content": "/guides/main_concepts/documents.html"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/guides/main_concepts/documents.html",
      "relativePath": "guides/main_concepts/documents.md",
      "key": "v-3312380f",
      "path": "/guides/main_concepts/documents.html",
      "headers": [
        {
          "level": 2,
          "title": "Documents structure",
          "slug": "documents-structure"
        }
      ],
      "lastUpdated": "1/10/2020, 3:49:20 PM"
    },
    {
      "title": "Main Concepts",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-02-10T15:55:55.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Main Concepts"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/guides/main_concepts/"
          },
          {
            "name": "twitter:title",
            "content": "Main Concepts"
          },
          {
            "name": "twitter:url",
            "content": "/guides/main_concepts/"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/guides/main_concepts/",
      "relativePath": "guides/main_concepts/README.md",
      "key": "v-af2dc878",
      "path": "/guides/main_concepts/",
      "headers": [
        {
          "level": 2,
          "title": "Glossary",
          "slug": "glossary"
        }
      ],
      "lastUpdated": "2/10/2020, 4:55:55 PM"
    },
    {
      "title": "Indexes",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-01-10T14:49:20.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Indexes"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/guides/main_concepts/indexes.html"
          },
          {
            "name": "twitter:title",
            "content": "Indexes"
          },
          {
            "name": "twitter:url",
            "content": "/guides/main_concepts/indexes.html"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/guides/main_concepts/indexes.html",
      "relativePath": "guides/main_concepts/indexes.md",
      "key": "v-0f21177f",
      "path": "/guides/main_concepts/indexes.html",
      "headers": [
        {
          "level": 2,
          "title": "Index UID and name",
          "slug": "index-uid-and-name"
        },
        {
          "level": 2,
          "title": "Schema definition",
          "slug": "schema-definition"
        },
        {
          "level": 3,
          "title": "Fields order",
          "slug": "fields-order"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example"
        },
        {
          "level": 2,
          "title": "Identifier",
          "slug": "identifier"
        },
        {
          "level": 2,
          "title": "Indexed",
          "slug": "indexed"
        },
        {
          "level": 2,
          "title": "Displayed",
          "slug": "displayed"
        },
        {
          "level": 2,
          "title": "Ranked",
          "slug": "ranked"
        },
        {
          "level": 2,
          "title": "Inferred Schema",
          "slug": "inferred-schema"
        },
        {
          "level": 3,
          "title": "Inference rules",
          "slug": "inference-rules"
        }
      ],
      "lastUpdated": "1/10/2020, 3:49:20 PM"
    },
    {
      "title": "Search",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-02-06T13:03:27.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Search"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/guides/main_concepts/search.html"
          },
          {
            "name": "twitter:title",
            "content": "Search"
          },
          {
            "name": "twitter:url",
            "content": "/guides/main_concepts/search.html"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/guides/main_concepts/search.html",
      "relativePath": "guides/main_concepts/search.md",
      "key": "v-4095e8e7",
      "path": "/guides/main_concepts/search.html",
      "headers": [
        {
          "level": 3,
          "title": "Finding documents",
          "slug": "finding-documents"
        },
        {
          "level": 3,
          "title": "Sorting documents",
          "slug": "sorting-documents"
        },
        {
          "level": 3,
          "title": "Search options",
          "slug": "search-options"
        }
      ],
      "lastUpdated": "2/6/2020, 2:03:27 PM"
    },
    {
      "title": "API References",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-02-10T15:55:55.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "API References"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/references/"
          },
          {
            "name": "twitter:title",
            "content": "API References"
          },
          {
            "name": "twitter:url",
            "content": "/references/"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/references/",
      "relativePath": "references/README.md",
      "key": "v-68195ce4",
      "path": "/references/",
      "headers": [
        {
          "level": 2,
          "title": "Recommended Headers",
          "slug": "recommended-headers"
        }
      ],
      "lastUpdated": "2/10/2020, 4:55:55 PM"
    },
    {
      "title": "Indexes",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-01-26T11:13:29.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Indexes"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/references/indexes.html"
          },
          {
            "name": "twitter:title",
            "content": "Indexes"
          },
          {
            "name": "twitter:url",
            "content": "/references/indexes.html"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/references/indexes.html",
      "relativePath": "references/indexes.md",
      "key": "v-99579e3e",
      "path": "/references/indexes.html",
      "headers": [
        {
          "level": 2,
          "title": "List all indexes",
          "slug": "list-all-indexes"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example"
        },
        {
          "level": 2,
          "title": "Get one index",
          "slug": "get-one-index"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example-2"
        },
        {
          "level": 2,
          "title": "Create an index",
          "slug": "create-an-index"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example-3"
        },
        {
          "level": 2,
          "title": "Update an index",
          "slug": "update-an-index"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example-4"
        },
        {
          "level": 2,
          "title": "Delete an index",
          "slug": "delete-an-index"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example-5"
        },
        {
          "level": 2,
          "title": "Get one index schema",
          "slug": "get-one-index-schema"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example-6"
        },
        {
          "level": 2,
          "title": "Update an index schema",
          "slug": "update-an-index-schema"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example-7"
        }
      ],
      "lastUpdated": "1/26/2020, 12:13:29 PM"
    },
    {
      "title": "Search",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-02-10T12:17:33.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Search"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/references/search.html"
          },
          {
            "name": "twitter:title",
            "content": "Search"
          },
          {
            "name": "twitter:url",
            "content": "/references/search.html"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/references/search.html",
      "relativePath": "references/search.md",
      "key": "v-fb437772",
      "path": "/references/search.html",
      "headers": [
        {
          "level": 2,
          "title": "Search in an index",
          "slug": "search-in-an-index"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example"
        }
      ],
      "lastUpdated": "2/10/2020, 1:17:33 PM"
    },
    {
      "title": "Health",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-01-26T11:13:29.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Health"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/references/health.html"
          },
          {
            "name": "twitter:title",
            "content": "Health"
          },
          {
            "name": "twitter:url",
            "content": "/references/health.html"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/references/health.html",
      "relativePath": "references/health.md",
      "key": "v-5c7cdbc7",
      "path": "/references/health.html",
      "headers": [
        {
          "level": 2,
          "title": "Get health",
          "slug": "get-health"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example"
        },
        {
          "level": 2,
          "title": "Update health",
          "slug": "update-health"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example-2"
        }
      ],
      "lastUpdated": "1/26/2020, 12:13:29 PM"
    },
    {
      "title": "Keys",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-01-26T11:13:29.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Keys"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/references/keys.html"
          },
          {
            "name": "twitter:title",
            "content": "Keys"
          },
          {
            "name": "twitter:url",
            "content": "/references/keys.html"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/references/keys.html",
      "relativePath": "references/keys.md",
      "key": "v-7dbe67f2",
      "path": "/references/keys.html",
      "headers": [
        {
          "level": 2,
          "title": "Get keys",
          "slug": "get-keys"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example"
        },
        {
          "level": 2,
          "title": "Get one key",
          "slug": "get-one-key"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example-2"
        },
        {
          "level": 2,
          "title": "Create Key",
          "slug": "create-key"
        },
        {
          "level": 3,
          "title": "Body",
          "slug": "body"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example-3"
        },
        {
          "level": 2,
          "title": "Update Key",
          "slug": "update-key"
        },
        {
          "level": 3,
          "title": "Body",
          "slug": "body-2"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example-4"
        },
        {
          "level": 2,
          "title": "Delete Key",
          "slug": "delete-key"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example-5"
        }
      ],
      "lastUpdated": "1/26/2020, 12:13:29 PM"
    },
    {
      "title": "Settings",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-01-26T11:13:29.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Settings"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/references/settings.html"
          },
          {
            "name": "twitter:title",
            "content": "Settings"
          },
          {
            "name": "twitter:url",
            "content": "/references/settings.html"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/references/settings.html",
      "relativePath": "references/settings.md",
      "key": "v-f56a1332",
      "path": "/references/settings.html",
      "headers": [
        {
          "level": 2,
          "title": "Get index settings",
          "slug": "get-index-settings"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example"
        },
        {
          "level": 2,
          "title": "Add or replace index settings",
          "slug": "add-or-replace-index-settings"
        },
        {
          "level": 3,
          "title": "Examples",
          "slug": "examples"
        }
      ],
      "lastUpdated": "1/26/2020, 12:13:29 PM"
    },
    {
      "title": "Stats",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-01-26T11:13:29.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Stats"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/references/stats.html"
          },
          {
            "name": "twitter:title",
            "content": "Stats"
          },
          {
            "name": "twitter:url",
            "content": "/references/stats.html"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/references/stats.html",
      "relativePath": "references/stats.md",
      "key": "v-aeb632ba",
      "path": "/references/stats.html",
      "headers": [
        {
          "level": 2,
          "title": "Get stat of an index",
          "slug": "get-stat-of-an-index"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example"
        },
        {
          "level": 2,
          "title": "Get stats of all indexes",
          "slug": "get-stats-of-all-indexes"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example-2"
        }
      ],
      "lastUpdated": "1/26/2020, 12:13:29 PM"
    },
    {
      "title": "Synonyms",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-01-26T11:13:29.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Synonyms"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/references/synonyms.html"
          },
          {
            "name": "twitter:title",
            "content": "Synonyms"
          },
          {
            "name": "twitter:url",
            "content": "/references/synonyms.html"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/references/synonyms.html",
      "relativePath": "references/synonyms.md",
      "key": "v-2dc08e07",
      "path": "/references/synonyms.html",
      "headers": [
        {
          "level": 2,
          "title": "List synonyms of one sequence",
          "slug": "list-synonyms-of-one-sequence"
        },
        {
          "level": 2,
          "title": "List all sequences and synonyms",
          "slug": "list-all-sequences-and-synonyms"
        },
        {
          "level": 2,
          "title": "Create synonyms",
          "slug": "create-synonyms"
        },
        {
          "level": 2,
          "title": "Update a synonym",
          "slug": "update-a-synonym"
        },
        {
          "level": 2,
          "title": "Delete a synonym",
          "slug": "delete-a-synonym"
        },
        {
          "level": 2,
          "title": "Batch write synonyms",
          "slug": "batch-write-synonyms"
        },
        {
          "level": 2,
          "title": "Clear synonyms",
          "slug": "clear-synonyms"
        }
      ],
      "lastUpdated": "1/26/2020, 12:13:29 PM"
    },
    {
      "title": "Stop words",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-02-05T17:04:34.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Stop words"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/references/stop_words.html"
          },
          {
            "name": "twitter:title",
            "content": "Stop words"
          },
          {
            "name": "twitter:url",
            "content": "/references/stop_words.html"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/references/stop_words.html",
      "relativePath": "references/stop_words.md",
      "key": "v-68ebe172",
      "path": "/references/stop_words.html",
      "headers": [
        {
          "level": 2,
          "title": "Get stop-words list",
          "slug": "get-stop-words-list"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example"
        },
        {
          "level": 2,
          "title": "Create stop-words list",
          "slug": "create-stop-words-list"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example-2"
        },
        {
          "level": 2,
          "title": "Delete stop-words list",
          "slug": "delete-stop-words-list"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example-3"
        }
      ],
      "lastUpdated": "2/5/2020, 6:04:34 PM"
    },
    {
      "title": "System information",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-01-26T11:13:29.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "System information"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/references/sys-info.html"
          },
          {
            "name": "twitter:title",
            "content": "System information"
          },
          {
            "name": "twitter:url",
            "content": "/references/sys-info.html"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/references/sys-info.html",
      "relativePath": "references/sys-info.md",
      "key": "v-6585f272",
      "path": "/references/sys-info.html",
      "headers": [
        {
          "level": 2,
          "title": "Get pretty system information",
          "slug": "get-pretty-system-information"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example"
        },
        {
          "level": 2,
          "title": "Get system information",
          "slug": "get-system-information"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example-2"
        }
      ],
      "lastUpdated": "1/26/2020, 12:13:29 PM"
    },
    {
      "title": "Version",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-01-26T11:13:29.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Version"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/references/version.html"
          },
          {
            "name": "twitter:title",
            "content": "Version"
          },
          {
            "name": "twitter:url",
            "content": "/references/version.html"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/references/version.html",
      "relativePath": "references/version.md",
      "key": "v-69a78931",
      "path": "/references/version.html",
      "headers": [
        {
          "level": 2,
          "title": "Get version of MeiliSearch",
          "slug": "get-version-of-meilisearch"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example"
        }
      ],
      "lastUpdated": "1/26/2020, 12:13:29 PM"
    },
    {
      "title": "Updates",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-01-26T11:13:29.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Updates"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/references/updates.html"
          },
          {
            "name": "twitter:title",
            "content": "Updates"
          },
          {
            "name": "twitter:url",
            "content": "/references/updates.html"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/references/updates.html",
      "relativePath": "references/updates.md",
      "key": "v-689c7d66",
      "path": "/references/updates.html",
      "headers": [
        {
          "level": 2,
          "title": "Get an update status",
          "slug": "get-an-update-status"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example"
        },
        {
          "level": 2,
          "title": "Get all update status",
          "slug": "get-all-update-status"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example-2"
        }
      ],
      "lastUpdated": "1/26/2020, 12:13:29 PM"
    },
    {
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-01-10T14:49:20.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/resources/"
          },
          {
            "name": "twitter:url",
            "content": "/resources/"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/resources/",
      "relativePath": "resources/README.md",
      "key": "v-74cc2d70",
      "path": "/resources/",
      "lastUpdated": "1/10/2020, 3:49:20 PM"
    },
    {
      "title": "Tutorials",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-03-03T15:43:36.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Tutorials"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/tutorials/"
          },
          {
            "name": "twitter:title",
            "content": "Tutorials"
          },
          {
            "name": "twitter:url",
            "content": "/tutorials/"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/tutorials/",
      "relativePath": "tutorials/README.md",
      "key": "v-3ff8c7e8",
      "path": "/tutorials/",
      "lastUpdated": "3/3/2020, 4:43:36 PM"
    },
    {
      "title": "Official SDKs / Libraries",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-01-26T10:57:49.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Official SDKs / Libraries"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/resources/sdks.html"
          },
          {
            "name": "twitter:title",
            "content": "Official SDKs / Libraries"
          },
          {
            "name": "twitter:url",
            "content": "/resources/sdks.html"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/resources/sdks.html",
      "relativePath": "resources/sdks.md",
      "key": "v-1ef205e6",
      "path": "/resources/sdks.html",
      "lastUpdated": "1/26/2020, 11:57:49 AM"
    },
    {
      "title": "Comming soon",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-01-24T17:44:20.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Comming soon"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/tutorials/cookbooks/"
          },
          {
            "name": "twitter:title",
            "content": "Comming soon"
          },
          {
            "name": "twitter:url",
            "content": "/tutorials/cookbooks/"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/tutorials/cookbooks/",
      "relativePath": "tutorials/cookbooks/README.md",
      "key": "v-45c8847c",
      "path": "/tutorials/cookbooks/",
      "headers": [
        {
          "level": 2,
          "title": "Comming soon",
          "slug": "comming-soon"
        }
      ],
      "lastUpdated": "1/24/2020, 6:44:20 PM"
    },
    {
      "title": "Comming soon",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-01-24T17:44:20.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Comming soon"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/tutorials/howtos/"
          },
          {
            "name": "twitter:title",
            "content": "Comming soon"
          },
          {
            "name": "twitter:url",
            "content": "/tutorials/howtos/"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/tutorials/howtos/",
      "relativePath": "tutorials/howtos/README.md",
      "key": "v-7cf8c264",
      "path": "/tutorials/howtos/",
      "headers": [
        {
          "level": 2,
          "title": "Comming soon",
          "slug": "comming-soon"
        }
      ],
      "lastUpdated": "1/24/2020, 6:44:20 PM"
    },
    {
      "title": "Quick Start",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-03-03T15:43:36.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Quick Start"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/tutorials/howtos/quickstart.html"
          },
          {
            "name": "twitter:title",
            "content": "Quick Start"
          },
          {
            "name": "twitter:url",
            "content": "/tutorials/howtos/quickstart.html"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/tutorials/howtos/quickstart.html",
      "relativePath": "tutorials/howtos/quickstart.md",
      "key": "v-56342967",
      "path": "/tutorials/howtos/quickstart.html",
      "headers": [
        {
          "level": 3,
          "title": "Deploy the Server",
          "slug": "deploy-the-server"
        },
        {
          "level": 3,
          "title": "Create an Index and Upload Some Documents",
          "slug": "create-an-index-and-upload-some-documents"
        },
        {
          "level": 3,
          "title": "Search for Documents",
          "slug": "search-for-documents"
        }
      ],
      "lastUpdated": "3/3/2020, 4:43:36 PM"
    },
    {
      "title": "Documents",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-01-26T11:13:29.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Documents"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/references/documents.html"
          },
          {
            "name": "twitter:title",
            "content": "Documents"
          },
          {
            "name": "twitter:url",
            "content": "/references/documents.html"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/references/documents.html",
      "relativePath": "references/documents.md",
      "key": "v-3f76bab1",
      "path": "/references/documents.html",
      "headers": [
        {
          "level": 2,
          "title": "Get one document",
          "slug": "get-one-document"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example"
        },
        {
          "level": 2,
          "title": "Get documents",
          "slug": "get-documents"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example-2"
        },
        {
          "level": 2,
          "title": "Add or replace documents",
          "slug": "add-or-replace-documents"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example-3"
        },
        {
          "level": 2,
          "title": "Add or update documents",
          "slug": "add-or-update-documents"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example-4"
        },
        {
          "level": 2,
          "title": "Delete all documents",
          "slug": "delete-all-documents"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example-5"
        },
        {
          "level": 2,
          "title": "Delete one document",
          "slug": "delete-one-document"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example-6"
        },
        {
          "level": 2,
          "title": "Delete documents",
          "slug": "delete-documents"
        },
        {
          "level": 3,
          "title": "Example",
          "slug": "example-7"
        }
      ],
      "lastUpdated": "1/26/2020, 12:13:29 PM"
    },
    {
      "title": "Search Parameters",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-01-26T11:13:29.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Search Parameters"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/guides/advanced_guides/search_parameters.html"
          },
          {
            "name": "twitter:title",
            "content": "Search Parameters"
          },
          {
            "name": "twitter:url",
            "content": "/guides/advanced_guides/search_parameters.html"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/guides/advanced_guides/search_parameters.html",
      "relativePath": "guides/advanced_guides/search_parameters.md",
      "key": "v-18f97512",
      "path": "/guides/advanced_guides/search_parameters.html",
      "headers": [
        {
          "level": 2,
          "title": "Query (q)",
          "slug": "query-q"
        },
        {
          "level": 2,
          "title": "Offset",
          "slug": "offset"
        },
        {
          "level": 2,
          "title": "Limit",
          "slug": "limit"
        },
        {
          "level": 2,
          "title": "Attributes to retrieve",
          "slug": "attributes-to-retrieve"
        },
        {
          "level": 2,
          "title": "Attributes to search in",
          "slug": "attributes-to-search-in"
        },
        {
          "level": 2,
          "title": "Attributes to crop",
          "slug": "attributes-to-crop"
        },
        {
          "level": 2,
          "title": "Crop length",
          "slug": "crop-length"
        },
        {
          "level": 2,
          "title": "Attributes to highlight",
          "slug": "attributes-to-highlight"
        },
        {
          "level": 2,
          "title": "Filters",
          "slug": "filters"
        },
        {
          "level": 2,
          "title": "Timeout",
          "slug": "timeout"
        },
        {
          "level": 2,
          "title": "Matches",
          "slug": "matches"
        }
      ],
      "lastUpdated": "1/26/2020, 12:13:29 PM"
    },
    {
      "title": "Comparison to alternatives",
      "frontmatter": {
        "meta": [
          {
            "property": "article:modified_time",
            "content": "2020-03-03T15:43:36.000Z"
          },
          {
            "property": "og:site_name",
            "content": "MeiliSearch Documentation"
          },
          {
            "property": "og:title",
            "content": "Comparison to alternatives"
          },
          {
            "property": "og:type",
            "content": "website"
          },
          {
            "property": "og:url",
            "content": "/resources/comparison_to_alternatives.html"
          },
          {
            "name": "twitter:title",
            "content": "Comparison to alternatives"
          },
          {
            "name": "twitter:url",
            "content": "/resources/comparison_to_alternatives.html"
          },
          {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        ]
      },
      "regularPath": "/resources/comparison_to_alternatives.html",
      "relativePath": "resources/comparison_to_alternatives.md",
      "key": "v-345cead2",
      "path": "/resources/comparison_to_alternatives.html",
      "headers": [
        {
          "level": 2,
          "title": "About MeiliSearch",
          "slug": "about-meilisearch"
        },
        {
          "level": 2,
          "title": "Comparisons",
          "slug": "comparisons"
        },
        {
          "level": 3,
          "title": "MeiliSearch vs. Elasticsearch",
          "slug": "meilisearch-vs-elasticsearch"
        },
        {
          "level": 3,
          "title": "MeiliSearch vs. Typesense",
          "slug": "meilisearch-vs-typesense"
        },
        {
          "level": 3,
          "title": "MeiliSearch vs. Algolia",
          "slug": "meilisearch-vs-algolia"
        },
        {
          "level": 2,
          "title": "A Quick Look at the Search Engine Landscape",
          "slug": "a-quick-look-at-the-search-engine-landscape"
        },
        {
          "level": 3,
          "title": "Open Source",
          "slug": "open-source"
        },
        {
          "level": 3,
          "title": "Closed Source",
          "slug": "closed-source"
        },
        {
          "level": 2,
          "title": "Conclusions",
          "slug": "conclusions"
        }
      ],
      "lastUpdated": "3/3/2020, 4:43:36 PM"
    }
  ],
  "themeConfig": {
    "repo": "meilisearch/MeiliSearch",
    "docsRepo": "meilisearch/documentation",
    "editLinks": true,
    "lastUpdated": "Last Updated",
    "logo": "/logo.png",
    "sidebarDepth": 1,
    "smoothScroll": true,
    "nav": [
      {
        "text": "Guides",
        "link": "/guides/"
      },
      {
        "text": "API References",
        "link": "/references/"
      },
      {
        "text": "Tutorials",
        "link": "/tutorials/"
      },
      {
        "text": "Resources",
        "link": "/resources/"
      }
    ],
    "sidebar": {
      "/guides/": [
        {
          "title": "🚀 Introduction",
          "path": "/guides/getting_started/",
          "collapsable": false,
          "children": [
            "/guides/getting_started/quick_start_guide",
            "/guides/getting_started/whats_next"
          ]
        },
        {
          "title": "💡 Main concepts",
          "path": "/guides/main_concepts/",
          "collapsable": false,
          "children": [
            "/guides/main_concepts/indexes",
            "/guides/main_concepts/documents",
            "/guides/main_concepts/search"
          ]
        },
        {
          "title": "📚 Advanced Guides",
          "path": "/guides/advanced_guides/",
          "collapsable": false,
          "children": [
            "/guides/advanced_guides/binary",
            "/guides/advanced_guides/typotolerance",
            "/guides/advanced_guides/concat",
            "/guides/advanced_guides/ranking",
            "/guides/advanced_guides/synonyms",
            "/guides/advanced_guides/stop_words",
            "/guides/advanced_guides/search_parameters",
            "/guides/advanced_guides/keys",
            "/guides/advanced_guides/prefix",
            "/guides/advanced_guides/distinct",
            "/guides/advanced_guides/asynchronous_updates",
            "/guides/advanced_guides/bucket_sort"
          ]
        }
      ],
      "/download/": [
        {
          "title": "Download",
          "path": "/download/"
        }
      ],
      "/references/": [
        {
          "title": "📒 API References",
          "path": "/references/",
          "collapsable": false,
          "children": [
            "/references/indexes",
            "/references/documents",
            "/references/search",
            "/references/synonyms",
            "/references/stop_words",
            "/references/updates",
            "/references/keys",
            "/references/settings",
            "/references/stats",
            "/references/health",
            "/references/version",
            "/references/sys-info"
          ]
        }
      ],
      "/tutorials/": [
        {
          "title": "🍳 Cookbooks",
          "path": "/tutorials/cookbooks/",
          "collapsable": false
        },
        {
          "title": "🧷 How to's",
          "path": "/tutorials/howtos/",
          "collapsable": false,
          "children": [
            "/tutorials/howtos/quickstart"
          ]
        }
      ],
      "/resources/": [
        {
          "title": "📦 Resources",
          "path": "/resources/",
          "collapsable": false,
          "children": [
            "/resources/sdks",
            "/resources/comparison_to_alternatives"
          ]
        }
      ]
    },
    "meilisearch": {
      "hostUrl": "https://e10b17e6.getmeili.com",
      "indexUid": "9tz3lqoi",
      "apiKey": "R62XWZPJG794YB5VFOADHTNQEKLCISM01U38"
    },
    "searchPlaceholder": "Search as you type..."
  }
}
